# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Options.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.resize(788, 255)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/options.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Options.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Options)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 861, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(510, 160, 271, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_button.setMinimumSize(QtCore.QSize(0, 70))
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 70))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 761, 121))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.switchpath = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.switchpath.setMinimumSize(QtCore.QSize(0, 35))
        self.switchpath.setObjectName("switchpath")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.switchpath)
        self.modspath = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.modspath.setMinimumSize(QtCore.QSize(0, 35))
        self.modspath.setObjectName("modspath")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.modspath)
        self.wiiupath = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.wiiupath.setMinimumSize(QtCore.QSize(0, 35))
        self.wiiupath.setObjectName("wiiupath")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wiiupath)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.wiiupath_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.wiiupath_browse.setMinimumSize(QtCore.QSize(120, 35))
        self.wiiupath_browse.setMaximumSize(QtCore.QSize(120, 16777215))
        self.wiiupath_browse.setObjectName("wiiupath_browse")
        self.verticalLayout.addWidget(self.wiiupath_browse, 0, QtCore.Qt.AlignRight)
        self.switchpath_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.switchpath_browse.setMinimumSize(QtCore.QSize(120, 35))
        self.switchpath_browse.setMaximumSize(QtCore.QSize(120, 16777215))
        self.switchpath_browse.setObjectName("switchpath_browse")
        self.verticalLayout.addWidget(self.switchpath_browse, 0, QtCore.Qt.AlignRight)
        self.modspath_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.modspath_browse.setMinimumSize(QtCore.QSize(120, 35))
        self.modspath_browse.setMaximumSize(QtCore.QSize(120, 16777215))
        self.modspath_browse.setObjectName("modspath_browse")
        self.verticalLayout.addWidget(self.modspath_browse, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Options)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "Form"))
        self.ok_button.setText(_translate("Options", "OK"))
        self.cancel_button.setText(_translate("Options", "Cancel"))
        self.label.setText(_translate("Options", "Wii-U dump path"))
        self.label_2.setText(_translate("Options", "Switch dump path"))
        self.label_3.setText(_translate("Options", "Mods output path"))
        self.wiiupath_browse.setText(_translate("Options", "Browse"))
        self.switchpath_browse.setText(_translate("Options", "Browse"))
        self.modspath_browse.setText(_translate("Options", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Options = QtWidgets.QWidget()
    ui = Ui_Options()
    ui.setupUi(Options)
    Options.show()
    sys.exit(app.exec_())
