# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Readme.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Readme")
        Form.resize(1057, 881)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-11, -11, 1101, 941))
        self.frame.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(96, 116, 165);\n"
"    /*color: white;*/\n"
"    color: black;\n"
"    border-style: none;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QAbstractScrollArea{ \n"
"    background-color: rgb(149, 165, 166);\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534, x2:1, y2:0.522, stop:0 rgba(46, 68, 91, 255), stop:1 rgba(101, 151, 200, 255));\n"
"}\n"
"\n"
"QTabWidget {\n"
"    background-color: rgb(91, 129, 165);\n"
"    color: black;\n"
"    border-color: rgb(60, 85, 109);\n"
"    gridline-color:  rgb(60, 85, 109);\n"
"    font: 8pt \"Segoe MDL2 Assets\";\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: rgb(79, 104, 191);\n"
"    color: white;\n"
"    border-color: rgb(60, 85, 109);\n"
"    gridline-color:  rgb(60, 85, 109);\n"
"font: 10pt \"Segoe MDL2 Assets\";\n"
"}\n"
"QLineEdit {\n"
"    background-color: rgb(149, 165, 166);\n"
"    color: white;\n"
"    border: none;\n"
"font: 10pt \"Segoe MDL2 Assets\";\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: rgb(81, 85, 93);\n"
"    color: white;\n"
"}\n"
" QTabBar::tab:!selected {\n"
"    background-color: rgb(138, 138, 138);\n"
"    color: white;\n"
"    }\n"
"\n"
"QFrame{\n"
"    background-color: rgb(47, 49, 54);\n"
"    color: white;\n"
"    \n"
"    font: 10pt \"Segoe MDL2 Assets\";\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: rgb(149, 165, 166);\n"
"    font: 10pt \"Segoe MDL2 Assets\";\n"
"}\n"
"\n"
"QLabel {\n"
"font: 10pt \"Segoe MDL2 Assets\";\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: rgb(149, 165, 166);\n"
"    border: none;\n"
"    font: 10pt \"Segoe MDL2 Assets\";\n"
"    color: white;\n"
"}\n"
"\n"
"    QComboBox QAbstractItemView::item\n"
"    {\n"
"      padding-top: 10px;\n"
"      padding-bottom: 10px;\n"
"    }\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"    border-color: rgb(60, 85, 109);\n"
"    gridline-color:  rgb(60, 85, 109);\n"
"    font: 10pt \"Segoe MDL2 Assets\";\n"
"}\n"
"QCheckBox {\n"
"    color: white;\n"
"    border-color: rgb(60, 85, 109);\n"
"    gridline-color:  rgb(60, 85, 109);\n"
"    font: 10pt \"Segoe MDL2 Assets\";\n"
"}\n"
"QTabWidget::pane { \n"
"border: 1; \n"
"border-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(255, 173, 0);\n"
"border-radius: 10px;\n"
"font: 11pt \"Segoe MDL2 Assets\";\n"
"    border: none;\n"
"font-weight: bold\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"                             {\n"
"                             background-color : rgb(244, 207, 0);\n"
"                             }\n"
"QMenuBar::item:pressed\n"
"                             {\n"
"                             background-color : rgb(149, 165, 166);\n"
"                             }\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.readme = QtWidgets.QTextBrowser(self.frame)
        self.readme.setGeometry(QtCore.QRect(20, 20, 1041, 861))
        self.readme.setObjectName("readme")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Readme", "Readme"))

class readme_window(QWidget, Ui_Form):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

    def load_txt(self):
        if os.path.exists('res\\Readme.txt'):
            with open('res\\Readme.txt','r') as f:
                self.readme.setPlainText(f.read())
        else:
            self.readme.setPlainText('')